### ISSUE TITLE
Resources need all parent resources

### ISSUE THREAD

**Issue by MariusDieckmann** [ArunaStorage/ArunaAPI#42]
If a resource is queried the response should contain all parent ids of associated resources.

**Comment by St4NNi** [comment]
# Problem

Currently all requests are build in a top->down perspective i.e. to query an object or object_group the parent collection must be specified, for collections the project must be specified etc. This behavior expects the user to know the context a request is issued in (collection / project) which is necessary in the current permission model. 

The overall problem with this is, if you just have a for example object_id it is not possible to query the associated hierarchy bottom->up to get the higher level organizational structures.  

# Draft idea

Provide a separate Service or RPC that allows a bottom up query:

- Specify a resource by id and the resource type
- Return a list of Hierarchies that contain the resource and all its "parent" structures.
- e.g. Object -> ObjectGroup(s) -> Collections -> Project(s)

# Problems and possible solutions

This should not be included in the default get requests because it is a dramatic change in behaviour from the users standpoint and makes the permission handling more complex. This is further complicated by the fact that associated higher level structures are not known in advance and therefore must be validated while they are queried and not beforehand, a possible security risk.

A short and easy solution would be requiring admin only permissions (which could be checked beforehand). But this would negate the overall usefulness of this request. 

For now the best solution would be a requirement to specify a project with read permissions and a small pre-flight check that tests if the requested resource (hierarchy) is part of the specified project.

**Comment by St4NNi** [comment]
Fixed in 0.5.0
