### ISSUE TITLE
Add replace option on objects

### ISSUE THREAD

**Issue by MariusDieckmann** [ArunaStorage/ArunaAPI#46]
There should either be and option to replace an object and delete the old one. This should may be the default.

**Comment by St4NNi** [comment]
What do you mean ? Replacing an object is already possible by deleting the old one and creating a new one. Maybe this could be combined in one request but this may be a pure convenience function with low priority. Any update / replacement / permanent modification of an object must create a new one or otherwise we will lose the strong focus in FAIR principles.
